services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Denisok94\SymfonyHelper\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources}'
